[tool.flet.app]
path = "cellsepi"

[tool.poetry]
name = "cellsepi"
version = "2.0"
description = "Segmentation of microscopy images and data analysis pipeline with a graphical user interface, powered by Cellpose."
authors = ["Jenna Ahlvers", "Santosh Chhetri Thapa", "Nike Dratt", "Pascal Heß", "Florian Hock"]
license = "Apache-2.0"
homepage = "https://github.com/CellSePi/CellSePi"
readme = "README.md"
packages = [
    { include = "cellsepi"}
]

[tool.poetry.scripts]
cellsepi = "cellsepi.main:main"

[[tool.poetry.include]]
path = "cellsepi/models/**/*"
[[tool.poetry.include]]
path = "cellsepi/csp.schema.json"